{% set name = "ParProcCo" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<310]

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - h5py >=3
    - pydantic >=2
    - pyyaml
    - requests

test:
  imports:
    - {{ name }}
  source_files:
    - tests
  requires:
    - parameterized
    - pytest
  commands:
    - pytest -vv tests/

about:
  home: https://github.com/DiamondLightSource/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Parallel Processing Coordinator'

  description:
    Parallel Processing Coordinator. Splits dataset processing to run parallel
    cluster jobs and aggregates outputs.
  doc_url: https://github.com/DiamondLightSource/{{ name }}/blob/master/README.md
  dev_url: https://github.com/DiamondLightSource/{{ name }}

extra:
  recipe-maintainers:
    - PeterC-DLS
    - VictoriaBeilsten-Edmands
