# generated by datamodel-codegen:
#   filename:  slurmdb-rest-44.yaml
#   timestamp: 2026-06-11T15:22:35+00:00

from __future__ import annotations
from pydantic import BaseModel, Field, RootModel

from slurm_rest import *

class OpenapiSlurmdbdPingResp(BaseModel):
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    pings: SlurmdbdPingArray
    """
    pings
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """


class OpenapiSlurmdbdQosRemovedResp(BaseModel):
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    removed_qos: StringList
    """
    removed QOS
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """


class OpenapiTresResp(BaseModel):
    TRES: TresList
    """
    TRES
    """
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """


class OpenapiUsersAddCondRespStr(BaseModel):
    added_users: str
    """
    added_users
    """
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """


class OpenapiWckeyRemovedResp(BaseModel):
    deleted_wckeys: StringList
    """
    deleted wckeys
    """
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """


class OpenapiAccountsAddCondResp(BaseModel):
    account: AccountShort | None = None
    """
    Account organization and description
    """
    association_condition: AccountsAddCond
    """
    CSV list of accounts, association limits and options, CSV list of clusters
    """
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """


class OpenapiAccountsAddCondRespStr(BaseModel):
    added_accounts: str
    """
    added_accounts
    """
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """


class OpenapiAccountsRemovedResp(BaseModel):
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    removed_accounts: StringList
    """
    removed_accounts
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """


class OpenapiAccountsResp(BaseModel):
    accounts: AccountList
    """
    accounts
    """
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """


class OpenapiAssocsRemovedResp(BaseModel):
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    removed_associations: StringList
    """
    removed_associations
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """


class OpenapiAssocsResp(BaseModel):
    associations: AssocList
    """
    associations
    """
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """


class OpenapiClustersRemovedResp(BaseModel):
    deleted_clusters: StringList
    """
    deleted_clusters
    """
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """


class OpenapiClustersResp(BaseModel):
    clusters: ClusterRecList
    """
    clusters
    """
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """


class OpenapiInstancesResp(BaseModel):
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    instances: InstanceList
    """
    instances
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """


class OpenapiJobModifyReq(BaseModel):
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    job_id_list: SelectedStepList | None = None
    """
    CSV list of Job IDs to modify
    """
    job_rec: JobModify | None = None
    """
    Job modify message
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """


class OpenapiJobModifyResp(BaseModel):
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    results: StringList
    """
    Job modify results
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """


class OpenapiSlurmdbdQosResp(BaseModel):
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    qos: QosList
    """
    List of QOS
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """


class OpenapiSlurmdbdStatsResp(BaseModel):
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    statistics: StatsRec
    """
    statistics
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """


class OpenapiUsersAddCondResp(BaseModel):
    association_condition: UsersAddCond
    """
    Filters to select associations for users
    """
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    user: UserShort
    """
    Admin level of user, DefaultAccount, DefaultWCKey
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """


class OpenapiWckeyResp(BaseModel):
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """
    wckeys: WckeyList
    """
    wckeys
    """


class OpenapiSlurmdbdConfigResp(BaseModel):
    accounts: AccountList | None = None
    """
    Accounts
    """
    associations: AssocList | None = None
    """
    Associations
    """
    clusters: ClusterRecList | None = None
    """
    Clusters
    """
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    instances: InstanceList | None = Field(None, deprecated=True)
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    qos: QosList | None = None
    """
    QOS
    """
    tres: TresList | None = None
    """
    TRES
    """
    users: UserList | None = None
    """
    Users
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """
    wckeys: WckeyList | None = None
    """
    WCKeys
    """


class OpenapiSlurmdbdJobsResp(BaseModel):
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    jobs: JobList
    """
    jobs
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """


class OpenapiUsersResp(BaseModel):
    errors: OpenapiErrors | None = None
    """
    Query errors
    """
    meta: OpenapiMeta | None = None
    """
    Slurm meta values
    """
    users: UserList
    """
    users
    """
    warnings: OpenapiWarnings | None = None
    """
    Query warnings
    """

